CREATE TABLE usuario (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR2(100) NOT NULL,
                         sobrenome VARCHAR2(100) NOT NULL,
                         email VARCHAR2(150) NOT NULL UNIQUE,
                         senha_hash VARCHAR2(255) NOT NULL,
                         objetivo VARCHAR2(50),
                         financas VARCHAR2(50),
                         perfil VARCHAR2(50)
);
